//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.github.fredjk_gh.PluginCommon.Data.Journals.FDevIDs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.github.fredjk_gh.PluginCommon.Data.Journals.FDevIDs.CSV", typeof(CSV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///Ammonia world,Ammonia world
        ///Sudarsky class I gas giant,Class I gas giant
        ///Sudarsky class II gas giant,Class II gas giant
        ///Sudarsky class III gas giant,Class III gas giant
        ///Sudarsky class IV gas giant,Class IV gas giant
        ///Sudarsky class V gas giant,Class V gas giant
        ///Earthlike body,Earth-like world
        ///Gas giant with ammonia based life,Gas giant with ammonia-based life
        ///Gas giant with water based life,Gas giant with water-based life
        ///Helium gas giant,Helium gas giant
        ///Helium rich gas giant,Helium-rich gas giant
        ///H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVBodies {
            get {
                return ResourceManager.GetString("CSVBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name,sku
        ///129030471,AX COMBAT JUMPSTART ALLIANCE CHIEFTAIN,FORC_FDEV_V_CHIEFTAIN_BUNDLE_001
        ///129030472,LASER MINING JUMPSTART TYPE-6,FORC_FDEV_V_TYPE6_BUNDLE_001
        ///129030473,EXPLORATION JUMPSTART DIAMONDBACK EXPLORER,FORC_FDEV_V_DIAMOND_EXPLORER_BUNDLE_001
        ///129030512,PYTHON MK II STELLAR,FORC_FDEV_V_PYTHON_MKII_BUNDLE_001
        ///129030519,PYTHON MK II STANDARD,FORC_FDEV_V_PYTHON_MKII_BUNDLE_002.
        /// </summary>
        internal static string CSVBundles {
            get {
                return ResourceManager.GetString("CSVBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number,name
        ///0,Harmless
        ///1,MostlyHarmless
        ///2,Novice
        ///3,Competent
        ///4,Expert
        ///5,Master
        ///6,Dangerous
        ///7,Deadly
        ///8,Elite
        ///9,Elite I
        ///10,Elite II
        ///11,Elite III
        ///12,Elite IV
        ///13,Elite V
        ///.
        /// </summary>
        internal static string CSVCombatRank {
            get {
                return ResourceManager.GetString("CSVCombatRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,symbol,category,name
        ///128049152,Platinum,Metals,Platinum
        ///128049153,Palladium,Metals,Palladium
        ///128049154,Gold,Metals,Gold
        ///128049155,Silver,Metals,Silver
        ///128049156,Bertrandite,Minerals,Bertrandite
        ///128049157,Indite,Minerals,Indite
        ///128049158,Gallite,Minerals,Gallite
        ///128049159,Coltan,Minerals,Coltan
        ///128049160,Uraninite,Minerals,Uraninite
        ///128049161,Lepidolite,Minerals,Lepidolite
        ///128049162,Cobalt,Metals,Cobalt
        ///128049163,Rutile,Minerals,Rutile
        ///128049165,Bauxite,Minerals,Bauxite
        ///128049166,Water,Chemi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVCommodity {
            get {
                return ResourceManager.GetString("CSVCommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number,name
        ///0,Helpless
        ///1,Mostly Helpless
        ///2,Amateur
        ///3,Semi Professional
        ///4,Professional
        ///5,Champion
        ///6,Hero
        ///7,Legend
        ///8,Elite
        ///9,Elite I
        ///10,Elite II
        ///11,Elite III
        ///12,Elite IV
        ///13,Elite V
        ///.
        /// </summary>
        internal static string CSVCQCRank {
            get {
                return ResourceManager.GetString("CSVCQCRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id
        ///assault
        ///collidedAtSpeedInNoFireZone
        ///collidedAtSpeedInNoFireZone_hulldamage
        ///disobeyPolice
        ///dockingMajorBlockingAirlock
        ///dockingMajorBlockingLandingPad
        ///dockingMajorTresspass
        ///dockingMinorBlockingAirlock
        ///dockingMinorBlockingLandingPad
        ///dockingMinorTresspass
        ///dumpingDangerous
        ///dumpingNearStation
        ///fireInNoFireZone
        ///fireInStation
        ///illegalCargo
        ///interdiction
        ///murder
        ///onFoot_arcCutterUse
        ///onFoot_breakingAndEntering
        ///onFoot_carryingIllegalData
        ///onFoot_carryingIllegalGoods
        ///onFoot_carryingStolenGoods
        ///onFoot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVCrimes {
            get {
                return ResourceManager.GetString("CSVCrimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id
        ///ActiveFighter
        ///Distance
        ///Hostile
        ///NoSpace
        ///Offences
        ///TooLarge
        ///RestrictedAccess.
        /// </summary>
        internal static string CSVDockingDeniedReasons {
            get {
                return ResourceManager.GetString("CSVDockingDeniedReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///$economy_Agri;,Agriculture
        ///$economy_Colony;,Colony
        ///$economy_Extraction;,Extraction
        ///$economy_HighTech;,High Tech
        ///$economy_Industrial;,Industrial
        ///$economy_Military;,Military
        ///$economy_None;,None
        ///$economy_Refinery;,Refinery
        ///$economy_Service;,Service
        ///$economy_Terraforming;,Terraforming
        ///$economy_Tourism;,Tourism
        ///$economy_Prison;,Prison
        ///$economy_Damaged;,Damaged
        ///$economy_Rescue;,Rescue
        ///$economy_Repair;,Repair
        ///$economy_Carrier;,Private Enterprise
        ///$economy_Engineer;,Engineering
        ///.
        /// </summary>
        internal static string CSVEconomy {
            get {
                return ResourceManager.GetString("CSVEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number,name
        ///0,None
        ///1,Outsider
        ///2,Serf
        ///3,Master
        ///4,Squire
        ///5,Knight
        ///6,Lord
        ///7,Baron
        ///8,Viscount
        ///9,Count
        ///10,Earl
        ///11,Marquis
        ///12,Duke
        ///13,Prince
        ///14,King
        ///.
        /// </summary>
        internal static string CSVEmpireRank {
            get {
                return ResourceManager.GetString("CSVEmpireRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,system_address,market_id,name
        ///300000,3932277478114,128673927,Didi Vatermann
        ///300010,1109989017963,128674183,Bill Turner
        ///300030,4481966019282,128674695,Broo Tarquin
        ///300040,2827992680811,128674951,The Sarge
        ///300050,6131367744226,128675207,Zacariah Nemo
        ///300080,1458309141194,128675975,Liz Ryder
        ///300090,1733321102034,128676231,Hera Tani
        ///300100,6681123623626,128676487,Felicity Farseer
        ///300110,3790082132323,128676743,Ram Tah
        ///300120,4305444669811,128676999,Lei Cheung
        ///300130,12274907287851,128677255,Petra  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVEngineers {
            get {
                return ResourceManager.GetString("CSVEngineers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number,name
        ///0,Aimless
        ///1,Mostly Aimless
        ///2,Scout
        ///3,Surveyor
        ///4,Explorer
        ///5,Pathfinder
        ///6,Ranger
        ///7,Pioneer
        ///8,Elite
        ///9,Elite I
        ///10,Elite II
        ///11,Elite III
        ///12,Elite IV
        ///13,Elite V
        ///.
        /// </summary>
        internal static string CSVExplorationRank {
            get {
                return ResourceManager.GetString("CSVExplorationRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///$faction_Alliance;,Alliance
        ///$faction_Empire;,Empire
        ///$faction_Federation;,Federation
        ///$faction_Independent;,Independent
        ///$faction_none;,None
        ///$faction_Pirate;,Pirate
        ///$faction_Thargoid;,Thargoid
        ///$faction_FrontlineSolutions;,Frontline Solutions
        ///
        ///.
        /// </summary>
        internal static string CSVFactionIds {
            get {
                return ResourceManager.GetString("CSVFactionIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///None,None
        ///Boom,Boom
        ///Bust,Bust
        ///CivilUnrest,Civil Unrest
        ///CivilWar,Civil War
        ///Election,Election
        ///Expansion,Expansion
        ///Famine,Famine
        ///Investment,Investment
        ///Lockdown,Lockdown
        ///Outbreak,Outbreak
        ///Retreat,Retreat
        ///War,War
        ///CivilLiberty,Civil Liberty
        ///PirateAttack,Pirate Attack
        ///Blight,Blight
        ///Drought,Drought
        ///InfrastructureFailure,Infrastructure Failure
        ///NaturalDisaster,Natural Disaster
        ///PublicHoliday,Public Holiday
        ///Terrorism,Terrorist Attack
        ///ColdWar,Cold War
        ///Colonisation,Colonisation
        ///HistoricEve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVFactionState {
            get {
                return ResourceManager.GetString("CSVFactionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number,name
        ///0,None
        ///1,Recruit
        ///2,Cadet
        ///3,Midshipman
        ///4,Petty Officer
        ///5,Chief Petty Officer
        ///6,Warrant Officer
        ///7,Ensign
        ///8,Lieutenant
        ///9,Lt Commander
        ///10,Post Commander
        ///11,Post Captain
        ///12,Rear Admiral
        ///13,Vice Admiral
        ///14,Admiral
        ///.
        /// </summary>
        internal static string CSVFederationRank {
            get {
                return ResourceManager.GetString("CSVFederationRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name,colony_range
        ///$Codex_Ent_Aleoids_Genus_Name;,Aleoida,150
        ///$Codex_Ent_Bacterial_Genus_Name;,Bacterium,500
        ///$Codex_Ent_Cactoid_Genus_Name;,Cactoida,300
        ///$Codex_Ent_Clypeus_Genus_Name;,Clypeus,150
        ///$Codex_Ent_Clepeus_Genus_Name;;,Clypeus,150
        ///$Codex_Ent_Conchas_Genus_Name;,Concha,150
        ///$Codex_Ent_Electricae_Genus_Name;,Electricae,1000
        ///$Codex_Ent_Fonticulus_Genus_Name;,Fonticulua,500
        ///$Codex_Ent_Shrubs_Genus_Name;,Frutexa,150
        ///$Codex_Ent_Fumerolas_Genus_Name;,Fumerola,100
        ///$Codex_Ent_Fungoids_Genus_Name;,Fungoida, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVGenuses {
            get {
                return ResourceManager.GetString("CSVGenuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///$government_Anarchy;,Anarchy
        ///$government_Communism;,Communism
        ///$government_Confederacy;,Confederacy
        ///$government_Cooperative;,Cooperative
        ///$government_Corporate;,Corporate
        ///$government_Democracy;,Democracy
        ///$government_Dictatorship;,Dictatorship
        ///$government_Feudal;,Feudal
        ///$government_Imperial;,Imperial
        ///$government_None;,None
        ///$government_Patronage;,Patronage
        ///$government_PrisonColony;,Prison Colony
        ///$government_Theocracy;,Theocracy
        ///$government_Engineer;,Engineer
        ///$government_Carrier;,Private O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVGovernment {
            get {
                return ResourceManager.GetString("CSVGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///$Faction_HappinessBand1;,Elated
        ///$Faction_HappinessBand2;,Happy
        ///$Faction_HappinessBand3;,Discontented
        ///$Faction_HappinessBand4;,Unhappy
        ///$Faction_HappinessBand5;,Despondent
        ///.
        /// </summary>
        internal static string CSVHappiness {
            get {
                return ResourceManager.GetString("CSVHappiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,symbol,rarity,type,category,name
        ///128672318,Iron,1,Raw,4,Iron
        ///128672319,Nickel,1,Raw,5,Nickel
        ///128672320,Tin,3,Raw,4,Tin
        ///128672321,Zinc,2,Raw,4,Zinc
        ///128672322,Carbon,1,Raw,1,Carbon
        ///128672323,Sulphur,1,Raw,3,Sulphur
        ///128672324,Phosphorus,1,Raw,2,Phosphorus
        ///128672325,Manganese,2,Raw,3,Manganese
        ///128672326,Selenium,4,Raw,4,Selenium
        ///128672327,Chromium,2,Raw,2,Chromium
        ///128672328,Vanadium,2,Raw,1,Vanadium
        ///128672329,Germanium,2,Raw,5,Germanium
        ///128672330,Cadmium,3,Raw,3,Cadmium
        ///128672331,Tungsten,3,Raw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVMaterial {
            get {
                return ResourceManager.GetString("CSVMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,symbol,category,English name
        ///128064021,graphene,Component,Graphene
        ///128672130,internalcorrespondence,Data,Internal Correspondence
        ///128932270,healthpack,Consumable,Medkit
        ///128941245,energycell,Consumable,Energy Cell
        ///128951161,amm_grenade_emp,Consumable,Shield Disruptor
        ///128951162,amm_grenade_frag,Consumable,Frag Grenade
        ///128951163,amm_grenade_shield,Consumable,Shield Projector
        ///128959449,chemicalsample,Item,Chemical Sample
        ///128961251,bypass,Consumable,E-Breach
        ///128961514,spyware,Data,Spyware
        ///128961524, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVMicroResources {
            get {
                return ResourceManager.GetString("CSVMicroResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,symbol,category,name,mount,guidance,ship,class,rating,entitlement
        ///128049250,SideWinder_Armour_Grade1,standard,Lightweight Alloy,,,Sidewinder,1,I,
        ///128049251,SideWinder_Armour_Grade2,standard,Reinforced Alloy,,,Sidewinder,1,I,
        ///128049252,SideWinder_Armour_Grade3,standard,Military Grade Composite,,,Sidewinder,1,I,
        ///128049253,SideWinder_Armour_Mirrored,standard,Mirrored Surface Composite,,,Sidewinder,1,I,
        ///128049254,SideWinder_Armour_Reactive,standard,Reactive Surface Composite,,,Sidewinder,1,I,
        ///128049256 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVOutfitting {
            get {
                return ResourceManager.GetString("CSVOutfitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fdname,name
        ///Business,Business
        ///Criminal,Criminal
        ///Explorer,Explorer
        ///HeadOfState,Head Of State
        ///Medical,Medical,
        ///MinorCelebrity,Minor Celebrity
        ///PoliticalPrisoner,Political Prisoner
        ///Politician,Politician
        ///POW,Prisoner of War
        ///Protester,Protester
        ///Refugee,Refugee
        ///Scientist,Scientist
        ///Security,Security
        ///Soldier,Soldier
        ///Terrorist,Terrorist
        ///Tourist,Tourist
        ///AidWorker,Aid Worker
        ///.
        /// </summary>
        internal static string CSVPassengers {
            get {
                return ResourceManager.GetString("CSVPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,symbol,market_id,category,name
        ///128666746,EraninPearlWhisky,128001536,Legal Drugs,Eranin Pearl Whisky
        ///128666747,LavianBrandy,128106744,Legal Drugs,Lavian Brandy
        ///128667019,HIP10175BushMeat,3223234816,Foods,HIP 10175 Bush Meat
        ///128667020,AlbinoQuechuaMammoth,3222822912,Foods,Albino Quechua Mammoth Meat
        ///128667021,UtgaroarMillenialEggs,128037120,Foods,Utgaroar Millennial Eggs
        ///128667022,WitchhaulKobeBeef,3223358720,Foods,Witchhaul Kobe Beef
        ///128667023,KarsukiLocusts,3225028096,Foods,Karsuki Locusts
        ///12866 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVRareCommodity {
            get {
                return ResourceManager.GetString("CSVRareCommodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name,number
        ///$Codex_RegionName_1;,Galactic Centre,1
        ///$Codex_RegionName_2;,Empyrean Straits,2
        ///$Codex_RegionName_3;,Ryker&apos;s Hope,3
        ///$Codex_RegionName_4;,Odin&apos;s Hold,4
        ///$Codex_RegionName_5;,Norma Arm,5
        ///$Codex_RegionName_6;,Arcadian Stream,6
        ///$Codex_RegionName_7;,Izanami,7
        ///$Codex_RegionName_8;,Inner Orion-Perseus Conflux,8
        ///$Codex_RegionName_9;,Inner Scutum-Centaurus Arm,9
        ///$Codex_RegionName_10;,Norma Expanse,10
        ///$Codex_RegionName_11;,Trojan Belt,11
        ///$Codex_RegionName_12;,The Veils,12
        ///$Codex_RegionName_13;,Newton&apos;s V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVRegions {
            get {
                return ResourceManager.GetString("CSVRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///eRingClass_Icy,Icy
        ///eRingClass_Metalic,Metallic
        ///eRingClass_MetalRich,Metal Rich
        ///eRingClass_Rocky,Rocky
        ///.
        /// </summary>
        internal static string CSVRings {
            get {
                return ResourceManager.GetString("CSVRings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///$SAA_SignalType_Biological;,Biological
        ///$SAA_SignalType_Geological;,Geological
        ///$SAA_SignalType_Guardian;,Guardian
        ///$SAA_SignalType_Human;,Human
        ///$SAA_SignalType_Other;,Other
        ///$SAA_SignalType_PlanetAnomaly;,Major Anomaly
        ///$SAA_SignalType_Thargoid;,Thargoid.
        /// </summary>
        internal static string CSVSaaSignals {
            get {
                return ResourceManager.GetString("CSVSaaSignals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///$GAlAXY_MAP_INFO_state_anarchy;,Anarchy
        ///$GALAXY_MAP_INFO_state_lawless;,Lawless
        ///$SYSTEM_SECURITY_high;,High
        ///$SYSTEM_SECURITY_low;,Low
        ///$SYSTEM_SECURITY_medium;,Medium
        ///.
        /// </summary>
        internal static string CSVSecurity {
            get {
                return ResourceManager.GetString("CSVSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,symbol,name,entitlement
        ///128049249,SideWinder,Sidewinder,
        ///128049255,Eagle,Eagle,
        ///128049261,Hauler,Hauler,
        ///128049267,Adder,Adder,
        ///128049273,Viper,Viper MkIII,
        ///128049279,CobraMkIII,Cobra MkIII,
        ///128049285,Type6,Type-6 Transporter,
        ///128049291,Dolphin,Dolphin,ELITE_HORIZONS_V_PLANETARY_LANDINGS
        ///128049297,Type7,Type-7 Transporter,
        ///128049303,Asp,Asp Explorer,
        ///128049309,Vulture,Vulture,
        ///128049315,Empire_Trader,Imperial Clipper,
        ///128049321,Federation_Dropship,Federal Dropship,
        ///128049327,Orca,Orca,
        ///128 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVShipyard {
            get {
                return ResourceManager.GetString("CSVShipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sku,requirement
        ///ELITE_HORIZONS_V_CAUSTIC_MEDIUM,unlocked via Human Tech Broker
        ///ELITE_HORIZONS_V_COBRA_MK_IV_1000,purchase base game and horizons before 5th Feb 2016 (PC) or 30th July 2016 (XBOX)
        ///ELITE_HORIZONS_V_CORROSIONCARGO_SIZE4,unlocked via Human Tech Broker
        ///ELITE_HORIZONS_V_FLECHETTE_FIXED_MEDIUM,unlocked via Human Tech Broker
        ///ELITE_HORIZONS_V_FLECHETTE_TURRET_MEDIUM,unlocked via Human Tech Broker
        ///ELITE_HORIZONS_V_GUARDIAN_FSDBOOSTER,unlocked via Guardian Tech Broker
        ///ELITE_HORIZONS_V_GUARDIAN_G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVSku {
            get {
                return ResourceManager.GetString("CSVSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Allegiance,Name
        ///Independent,Independent
        ///PilotsFederation,Pilots Federation
        ///Federation,Federation
        ///Empire,Empire
        ///Alliance,Alliance
        ///Guardian,Guardian
        ///Thargoid,Thargoid
        ///PlayerPilots,Player Pilots
        ///.
        /// </summary>
        internal static string CSVSystemAllegiance {
            get {
                return ResourceManager.GetString("CSVSystemAllegiance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id,name
        ///Terraformable,Terraformable
        ///Terraformed,Terraformed
        ///Terraforming,Terraforming
        ///.
        /// </summary>
        internal static string CSVTerraformingState {
            get {
                return ResourceManager.GetString("CSVTerraformingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number,name
        ///0,Penniless
        ///1,Mostly Penniless
        ///2,Peddler
        ///3,Dealer
        ///4,Merchant
        ///5,Broker
        ///6,Entrepreneur
        ///7,Tycoon
        ///8,Elite
        ///9,Elite I
        ///10,Elite II
        ///11,Elite III
        ///12,Elite IV
        ///13,Elite V
        ///.
        /// </summary>
        internal static string CSVTradeRank {
            get {
                return ResourceManager.GetString("CSVTradeRank", resourceCulture);
            }
        }
    }
}
